### PR TITLE
 Updated AdminPagesRestrictMiddleware 

### PR DESCRIPTION
**Pull request by pedfercue**
Updated AdminPagesRestrictMiddleware so it works with the new Django middleware style from Django 1.10 but also keeps working with older versions.

### CODE REVIEW

**Comment by robromano** [comment]
Thank you for the contribution. Looks like the Travis CI builds didn’t pass
with this change for some Django versions — can’t import module
django.urls, can you look into fixing these as well?

Thanks again!

**Comment by pedfercue** [comment]
The Travis build is passing now. 
The error was due to an import which works on django >= 1.10 but not on previous versions

**Comment by pedfercue** [comment]
Thank you for merging this!
Do you have plans for your next release? I'd be interested in upgrading this package if there's a new release.
Thank you for your work

**Comment by robromano** [comment]
I made a new release to PyPI which is now version 2, you should be good to upgrade to it.

Do you have any other feature ideas?  Maybe better audit trail of what happened and possibly banning repeated login attempts (sort of like what  fail2ban package does on Linux ).

**Pull request merged**
