### PR TITLE
When the AllowedIP table is empty the middleware was blocking the ope…

### PR DESCRIPTION
**Pull request by raurope**
…rations create, modify or delete in other tables

### CODE REVIEW

**Comment by robromano** [comment]
Thanks for the pull request.   I think the behavior was by design.  I assumed the user would have put in some allows IP addresses or a "*" after running syncdb but before activating the middleware in settings.  I guess the docs didn't make this clear.

I think your change is okay but the docs should be updated to make it really clear to the user what to do.  Would you mind enhancing the docs with this?

Also Travis shows a unittest failure in your pull request, probably just needs updating.  See the test_blocked_ip unittest.  Can you fix this too?

Feel free to add a CONTRIBUTORS.txt file and put your info in the file.  

Your help is much appreciated.

**Comment by raurope** [comment]
Hi Rob, 

Although it was done by definition I believe that is more useful don't block ips when the database is empty. The changes are focused in add this feature. If you think otherwise you can reject the pull request. Thank you very much for your answer.

**Comment by robromano** [comment]
I would like to accept your improvements.  If you have a chance please fix
the unittest and adjust the readme to explain the new behavior, and we can
merge this in.  And definitely add a CREDITS or CONTRIBUTORS file with your
GitHub ID :)

Thanks

**Comment by raurope** [comment]
Hi Rob,

it's done. The 9686519 solves the tests problems and 9bbd2f4 has the READme updated. I guess that you haven't seen them?

Thanks

**Comment by robromano** [comment]
Thanks, I didn't see them, much appreciated!

**Comment by raurope** [comment]
Hi Rob,

You're welcome, if you need something else, please contact me.

Regards.

**Comment by robromano** [comment]
Bumped version to 1.0.2 with all latest changes and pushed to PyPi

https://pypi.python.org/pypi/django-adminrestrict/1.0.2

**Pull request merged**
