### PR TITLE
Add fields to monitor creator and editor of the AllowedIP

### PR DESCRIPTION
**Pull request by lmarvaud**
Additionnally add a description of the AllowedIP

### CODE REVIEW

**Comment by lmarvaud** [comment]
Note: This pull request (https://github.com/robromano/django-adminrestrict/pull/11) requires to be validated for the travis tests to pass

**Comment by robromano** [comment]
Thanks for the contribution.  Do we need to update anything for the Travis build to pass first?

**Comment by lmarvaud** [comment]
Actually the master branch is red [Build Status](https://travis-ci.org/robromano/django-adminrestrict)
Please accept and merge the PR https://github.com/robromano/django-adminrestrict/pull/11 to validate the current branch.

**Comment by robromano** [comment]
I merged PR #11 but still not getting Travis CI to pass for all Django versions.

**Pull request closed without merging**
