### PR TITLE
Allow IPv6 addresses to access the admin

### PR DESCRIPTION
**Pull request by primal100**

### CODE REVIEW

**Review by robromano — APPROVED** [review]

**Comment by robromano** [comment]
Thanks - great idea. We can make a new release soon with all these  enhancements.

**Comment by robromano** [comment]
Do you think the private IP prefixes in get_ip_address_from_request() need updating to support IPv6?

**Comment by primal100** [comment]
> Do you think the private IP prefixes in get_ip_address_from_request() need updating to support IPv6?

Yes we can add that. But I wasn't sure about the ranges so I didn't include it yet. I believe fd00::/8 is the private address range that should be safe to add if you agree.

**Comment by robromano** [comment]
The equivalent in ipv6 are ULAs: Unique Local Addresses, which is covered
in RFC4193.

The prefix is *fc00::/7*

We can add this RFC to the docs where we mention RFC1918 for ipv4.

**Comment by primal100** [comment]
OK I can handle that!

**Comment by primal100** [comment]
So I've been looking at the code and while there is a list of private IP prefxes in the middleware.py module, the test for whether or not to allow access uses the is_private attribute in the python standard library ipaddress module. Here is the full list of private IP addresses that will pass the is_private test for ipv6

 https://github.com/python/cpython/blob/9510e6f3c797b4398aaf58abc1072b9db0a644f9/Lib/ipaddress.py


  ```python
 _private_networks = [
        IPv6Network('::1/128'),
        IPv6Network('::/128'),
        IPv6Network('::ffff:0:0/96'),
        IPv6Network('100::/64'),
        IPv6Network('2001::/23'),
        IPv6Network('2001:2::/48'),
        IPv6Network('2001:db8::/32'),
        IPv6Network('2001:10::/28'),
        IPv6Network('fc00::/7'),
        IPv6Network('fe80::/10'),
        ]
```

They are taken from here. The 2001 net is assigned for documentation. fe80 is link local unicast. Are we ok to add all of these as acceptable?

https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml

Also can I ask what is the purpose of PRIVATE_IPS_PREFIX? It's not actually used for the condition to see if the IP address is allowed. Just that those IP's do not have strip() applied to them. What is the reason and is it necessary for IPv6?

**Comment by robromano** [comment]
Thanks for researching this.  Glad to see that we're already using `is_private` from the library, as it looks like it is way more up to date and supports IPv6.  So that's good news!

It seems like the problem is our function `get_ip_address_from_request()` has the hard-coded list PRIVATE_IPS_PREFIX and it's out of date.

I was looking into a better way to extract the client's IP address from headers. I came across this Django module:
https://github.com/un33k/django-ipware

It's interesting that they maintain their own prefixes for IPv4 and IPv6 there. Not sure why.  

I'm open to rewriting `get_ip_address_from_request()` to support IPv6 by using django-ipware, but we'd add it as a dependency. What do you think?

**Comment by primal100** [comment]
If it's just for Private IP addresses, I think what is in cpython for ```is_private``` will work fine. But using ipware would reduce the amount of code maintenaince within django-adminrestrict which I suppose is a good thing.

One difference is that django-adminrestrict searches through all the IP addresses to until it finds a valid non-private one, whereas with IPware you can specify how many proxies there are before getting to the one IP address you want to check (and also to set header priority). So yeah ipware is probably a better solution overall.

**Pull request merged**
